package com.fksoft.domain.booking;

import java.util.UUID;

/**
 * Booking locator value object (BR3): an origin plus a non-empty code, unique per {@code (origin,
 * code)}. INTERNAL locators are generated by the system; EXTERNAL ones are typed by the operator
 * and must be non-empty.
 *
 * @param origin where the code comes from
 * @param code the locator code (non-empty)
 */
public record Locator(LocatorOrigin origin, String code) {

  public Locator {
    if (origin == null || code == null || code.isBlank()) {
      throw new BookingLocatorInvalidException();
    }
    code = code.trim();
  }

  /** An external locator with an operator-typed code (must be non-empty). */
  public static Locator external(String code) {
    return new Locator(LocatorOrigin.EXTERNAL, code);
  }

  /** A freshly generated internal locator. */
  public static Locator internalGenerated() {
    return new Locator(
        LocatorOrigin.INTERNAL,
        "INT-" + UUID.randomUUID().toString().substring(0, 8).toUpperCase());
  }
}
