package com.fksoft.domain.booking;

/**
 * Where a booking's locator comes from (BR3): {@link #INTERNAL} is generated by the system, {@link
 * #EXTERNAL} is typed by the operator (from a portal/voucher). External value is the name.
 */
public enum LocatorOrigin {
  INTERNAL,
  EXTERNAL
}
